---
- name: Set Up Developer Tools on Windows
  hosts: tag_environment_dev
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
  roles:
    - role: windows_devtools
