---
- name: Apply Windows Updates
  hosts: windows
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
  roles:
    - role: windows_updates
