---
- name: Create an Empty Azure Resource Group
  hosts: localhost
  vars_prompt:
    - name: resource_group_name
      prompt: Specify the name for the resource group
      private: false
    - name: location
      prompt: Specify the location for the resource group
      private: false
  vars:
    group_tags:
      source: ansible-azure
  roles:
    - role: azure_resource_group
