---
- name: Azure Resource Group
  hosts: localhost
  vars_prompt:
    - name: group_name
      prompt: Specify the name for the resource group
      private: false
    - name: location
      prompt: Specify the location for the resource group
      private: false
  vars:
    group_tags:
      - key: source
        value: ansible
  roles:
    - role: azure_resource_group
