---
- name: Deploy Example Windows VM
  hosts: localhost
  vars_prompt:
    - name: admin_username
      prompt: The admin username for the Virtual Machine
      private: false
    - name: admin_password
      prompt: The admin password for the Virtual Machine
      private: true
    - name: enable_acc_net
      prompt: Enable accelerated networking?
      private: false
    - name: location
      prompt: The location for the resources
      private: false
    - name: network_security_group_id
      prompt: ID of the Network Security Group
      private: false
    - name: os_disk_type
      prompt: OS Disk storage type
      private: false
    - name: os_version
      prompt: The Windows version for the VM
      private: false
    - name: public_ip_address_type
      prompt: Public IP address type
      private: false
    - name: public_ip_address_sku
      prompt: Public IP address type SKU
      private: false
    - name: storage_account_name
      prompt: Name of the storage account for diagnostics
      private: false
    - name: subnet_name
      prompt: Name of the subnet
      private: false
    - name: vm_name
      prompt: Name of the virtual machine
      private: false
    - name: vm_resource_group_name
      prompt: Resource group for the VM resources
      private: false
    - name: vm_size
      prompt: Size of the virtual machine
      private: false
    - name: vnet_id
      prompt: ID of the virtual network
      private: false
    - name: key_vault_name
      prompt: Name of the Key Vault
      private: false
    - name: key_vault_rg_name
      prompt: Resource Group containing the Key Vault
      private: false
    - name: pfx_passwd
      prompt: Password for the certificates PFX file
      private: true

  vars:
    computer_name: "{{ vm_name }}"
    computer_fqdn_name: "{{ computer_name }}.{{ dns_domain }}"
    deployment_name: "{{ vm_name }}-{{ subnet_name }}-{{ location }}"
    cert_country_name: GB
    dns_domain: "{{ location }}.cloudapp.azure.com"
    enable_hot_patching: false
    network_interface_name: "{{ vm_name }}-nic0"
    nic_delete_option: Delete
    output_dir: tmp
    os_disk_size: 127
    os_disk_delete_option: Delete
    patch_mode: AutomaticByOS
    pip_delete_option: Delete
    public_ip_address_name: "{{ vm_name }}-pip0"
    resource_tags:
      environment: dev
      phase: poc
    secret_encoding: base64
    secret_file: "{{ computer_name }}-secret-b64.txt"
    secret_name: "{{ computer_name }}-winrm"
    winrm_cert_store_name: "My"

  roles:
    - role: local_winrm_server_cert_gen
    - role: key_vault_secret
    - role: windows_single_public_vm
