---
- name: Deploy Certificate for WinRM
  hosts: localhost
  vars_prompt:
    - name: cert_prefix
      prompt: Prefix for the certificate names
      private: false
    - name: username
      prompt: Admin username for the Virtual Machine
      private: false
    - name: key_vault_name
      prompt: Name of the Key Vault
      private: false
    - name: pfx_passwd
      prompt: Password for the certificates PFX file
      private: true
  vars:
    output_dir: tmp
    secret_name: "{{ cert_prefix }}-winrm"
  roles:
    - role: local_cert_gen
    - role: key_vault_secret
