---
- name: Deploy WinRM Server Certificate to Key Vault
  hosts: localhost
  vars_prompt:
    - name: computer_name
      prompt: Name of the server
      private: false
    - name: dns_domain
      prompt: DNS domain for the server
      private: false
    - name: cert_country_name
      prompt: Country name for certificate
      private: false
    - name: key_vault_name
      prompt: Name of the Key Vault
      private: false
    - name: key_vault_rg_name
      prompt: Resource Group containing the Key Vault
      private: false
    - name: pfx_password
      prompt: Password for the certificates PFX file
      private: true
  vars:
    computer_fqdn_name: "{{ computer_name }}.{{ dns_domain }}"
    output_dir: tmp
    secret_file: "{{ computer_name }}-secret-base64.txt"
    secret_name: "{{ computer_name }}-winrm"
  roles:
    - role: local_winrm_server_cert_gen
    - role: azure_key_vault_secret_file
