---
- name: Deploy Azure Key Vault
  hosts: localhost
  vars_prompt:
    - name: key_vault_name
      prompt: The name of the key vault
      private: false
    - name: key_vault_rg_name
      prompt: The name of the key vault
      private: false
    - name: operators_id
      prompt: Identity in Azure Active Directory for the vault
      private: false
    - name: certificates_permissions
      prompt: The permissions to certificates in the vault
      private: true
    - name: keys_permissions
      prompt: The permissions to keys in the vault
      private: true
    - name: secrets_permissions
      prompt: The permissions to secrets in the vault
      private: false
    - name: location
      prompt: The location for the resources
      private: false
    - name: vault_sku
      prompt: The SKU for the key vault
      private: false

  vars:
    deployment_name: "{{ key_vault_name }}-{{ location }}"
    resource_tags:
      environment: dev
      phase: poc

  roles:
    - role: azure_minimal_key_vault
