namespace: "stuartellis"
name: "stuartellis-azure"
description: "Custom Ansible for Azure"
version: "1.0.0"
readme: "README.md"
authors:
    - "Stuart Ellis <stuart@stuartellis.name>"
dependencies:
    "ansible.windows": ">=1.9.0"
    "azure.azcollection": ">=1.11.0"
    "chocolatey.chocolatey": ">=1.2.0"
license:
    - "MIT"
tags:
    - azure
repository: "https://www.github.com/stuartellis/ansible-azure"
