namespace: "stuartellis"
name: "stuartellis-azure"
description: "Custom Ansible for Azure"
version: "0.0.1"
readme: "README.md"
authors:
    - "Stuart Ellis <stuart@stuartellis.name>"
dependencies:
    "azure.azcollection": ">=1.11.0"
license:
    - "MIT"
tags:
    - azure
repository: "https://www.github.com/stuartellis/ansible-azure"