---
- hosts: windows
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
  tasks:
    - name: Test connection
      ansible.windows.win_ping:
