---
- name: Set secret in Key Vault from {{ secret_file }}
  delegate_to: localhost
  ansible.builtin.command:
    chdir: "{{ working_dir.path }}"
    cmd: |
      az keyvault secret set --name {{ secret_name }} -o json --vault-name {{ key_vault_name }} --file {{ secret_file }}
  args:
    warn: false
  register: vault_secret

- name: Set secret URL as a fact
  ansible.builtin.set_fact: secret_url="{{ vault_secret.stdout | from_json | json_query('id') }}"
