---
- name: Deploy {{ vm_name }} to {{ vm_resource_group_name }} in {{ location }}
  azure.azcollection.azure_rm_deployment:
    state: present
    deployment_mode: incremental
    deployment_name: "{{ deployment_name }}"
    resource_group_name: "{{ vm_resource_group_name }}"
    location: "{{ location }}"
    template: "{{ lookup('file', 'vm-deployment-template.json') }}"
    parameters:
      adminUsername:
        value: "{{ admin_username }}"
      adminPublicKey:
        value: "{{ ssh_public_key }}"
      diagnosticsStorageAccountName:
        value: "{{ storage_account_name }}"
      enableAcceleratedNetworking:
        value: "{{ enable_acc_net }}"
      imageReference:
        value: "{{ image_reference }}"
      location:
        value: "{{ location }}"
      networkInterfaceName:
        value: "{{ network_interface_name }}"
      networkSecurityGroupId:
        value: "{{ network_security_group_id }}"
      nicDeleteOption:
        value: "{{ nic_delete_option }}"
      osDiskDeleteOption:
        value: "{{ os_disk_delete_option }}"
      osDiskSize:
        value: "{{ os_disk_size }}"
      osDiskType:
        value: "{{ os_disk_type }}"
      patchMode:
        value: "{{ patch_mode }}"
      pipDeleteOption:
        value: "{{ pip_delete_option }}"
      publicIpAddressName:
        value: "{{ public_ip_address_name }}"
      publicIpAddressSku:
        value: "{{ public_ip_address_sku }}"
      publicIpAddressType:
        value: "{{ public_ip_address_type }}"
      resourceTags:
        value: "{{ resource_tags }}"
      subnetName:
        value: "{{ subnet_name }}"
      virtualMachineComputerName:
        value: "{{ vm_name }}"
      virtualMachineName:
        value: "{{ vm_name }}"
      virtualMachineSize:
        value: "{{ vm_size }}"
      virtualNetworkId:
        value: "{{ vnet_id }}"
