---
- name: Deploy {{ key_vault_name }} to {{ key_vault_rg_name }} in {{ location }}
  azure.azcollection.azure_rm_deployment:
    state: present
    deployment_mode: incremental
    deployment_name: "{{ deployment_name }}"
    resource_group_name: "{{ key_vault_rg_name }}"
    location: "{{ location }}"
    template: "{{ lookup('file', 'deployment-template.json') }}"
    tags: "{{ group_tags | items2dict }}"
    parameters:
      location:
        value: "{{ location }}"
      operatorsId:
        value: "{{ object_id }}"
      keyVaultName:
        value: "{{ key_vault_name }}"
      certificatesPermissions:
        value: "{{ certificates_permissions }}"
      keysPermissions:
        value: "{{ keys_permissions }}"
      secretsPermissions:
        value: "{{ secrets_permissions }}"
      vaultSku:
        value: "{{ vault_sku }}"
