---
- name: Set secret in Key Vault
  delegate_to: localhost
  ansible.builtin.command:
    chdir: "{{ working_dir.path }}"
    cmd: "az keyvault secret set --name {{ secret_name }} --vault-name {{ key_vault_name }} --file {{ secret_file }}"
  register: vault_secret
