---
- name: Ensure resource group {{ resource_group_name }} in {{ location }}
  azure.azcollection.azure_rm_resourcegroup:
    name: "{{ resource_group_name }}"
    location: "{{ location }}"
    state: present
    tags: "{{ resource_tags }}"
